### PR TITLE
make this pkg noarch

### LINKED ISSUE #41: why not make this noarch?
Your pypi wheel is no arch and your package seems like it is pure python.

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by ngam**
Fixes #41 

As a starting example. You should probably add some tests... 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by lululxvi** [comment]
I see there is a test on pytorch. pytorch is installed via
```
conda install pytorch cpuonly -c pytorch
```
https://pytorch.org/get-started/locally/

**Comment by ngam** [comment]
> I see there is a test on pytorch. pytorch is installed via
> 
> ```
> conda install pytorch cpuonly -c pytorch
> ```
> 
> https://pytorch.org/get-started/locally/

We can get it from conda-forge. It should work fine.

**Comment by ngam** [comment]
Why did you need the extra yum_reqs btw?

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by lululxvi** [comment]
> Why did you need the extra yum_reqs btw?

This is not created by me. It is by regro-cf-autotick-bot on Feb 14, 2020 with the commit message "use matplotlib-base instead of matplotlib"

**Comment by ngam** [comment]
> use matplotlib-base instead of matplotlib

Ah!

**Comment by ngam** [comment]
Okay, I have something working locally. I will make edits soon and I am going to add a few more tests.

**Comment by ngam** [comment]
@lululxvi, there is a lot of noise in this PR, but you should pay attention to the following points before you merge:
- [x] I removed the numpy pin --- do you need it at all?
- [x] This can safely be packaged as noarch --- do you have any non-python files in your repo?
- [x] I removed the yum_reqs stuff, I don't think you need them. But it is hard to tell without proper matplotlib testing --- maybe we could add a test for that? I don't think it is needed, but I can double-check for you
- [x] I added two tests straight from your docs; maybe you could add more if you want.

**Comment by ngam** [comment]
> added two tests straight from your docs; maybe you could add more if you want

testing tensorflow is really challenging. I recommend you stick to testing only pytorch here. The reason is that tensorflow-probability depends on tensorflow in weird ways and you will likely not be able to install the correct ones all the time. 


I get this error locally:
```
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.6; Detected an installation of version 2.4.3. Please upgrade TensorFlow to proceed.

```

The pytorch test works fine:

```
+ export DDEBACKEND=pytorch
+ DDEBACKEND=pytorch
+ python -c 'import deepxde; print(deepxde.__version__)'
Using backend: pytorch

0.14.1
+ python test_pytorch.py
Using backend: pytorch

/Users/ngam/.Mambaforge-MacOSX-x86_64/envs/blds/conda-bld/deepxde_1641441892309/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/skopt/sampler/sobol.py:246: UserWarning: The balance properties of Sobol' points require n to be a power of 2. 0 points have been previously generated, then: n=0+18=18. 
  warnings.warn("The balance properties of Sobol' points require "
Compiling model...
'compile' took 0.000065 s

Training model...

Step      Train loss              Test loss               Test metric   
0         [4.71e+01, 3.03e-02]    [4.97e+01, 3.03e-02]    [1.12e+00]    
1000      [3.27e-04, 2.64e-07]    [5.58e-04, 2.64e-07]    [1.14e-03]    
2000      [8.30e-05, 7.57e-09]    [2.19e-04, 7.57e-09]    [2.43e-04]    
3000      [2.61e-05, 9.88e-09]    [1.15e-04, 9.88e-09]    [3.50e-04]    
4000      [5.24e-05, 8.21e-07]    [1.29e-04, 8.21e-07]    [1.20e-03]    
5000      [2.37e-05, 1.30e-06]    [9.11e-05, 1.30e-06]    [1.59e-03]    
6000      [1.83e-03, 1.79e-04]    [1.40e-03, 1.79e-04]    [1.25e-02]    
7000      [4.36e-03, 6.50e-04]    [2.83e-03, 6.50e-04]    [2.33e-02]    
8000      [5.73e-06, 6.11e-11]    [5.02e-05, 6.11e-11]    [3.18e-04]    
9000      [4.55e-05, 4.74e-06]    [3.98e-05, 4.74e-06]    [1.79e-03]    
10000     [1.05e-05, 2.74e-07]    [5.44e-05, 2.74e-07]    [4.76e-04]    

Best model at step 8000:
  train loss: 5.73e-06
  test loss: 5.02e-05
  test metric: [3.18e-04]

'train' took 16.525849 s


```

**Comment by lululxvi** [comment]
Yes, it is totally OK to only test pytorch.

**Comment by ngam** [comment]
> Yes, it is totally OK to only test pytorch.

Somehow the tf tests passed, but if you look inside the logs, you will see it relied on the cuda-enabled 2.6.2 tf for it to work. With the cpu version of tf (from conda-forge) it won't succeed, I think. (The TF build from conda-forge can be problematic)

**Comment by ngam** [comment]
Anyway, good work --- I read your pinns paper a while back and I am looking forward to using deepxde in the future (and maybe even contribute to it).

Feel free to edit this PR and merge whenever you feel comfortable with it. 👍

**Comment by lululxvi** [comment]
Sometimes the TF built from conda-forge is problematic (especially starting from TF v2), and I didn't find a way to resolve it. That is why I removed all the tests.

I am glad to know that you know PINNs. It would be great if you would contribute to DeepXDE in the future. I am also looking forward to it. In addition to adding more scientific features, I also plan to add the support of Jax.

**Pull request merged**
